export const USER_STREAK = 'USER_STREAK';
export const USER_XP = 'USER_XP';
export const BOOKMARKS_NOTES = 'BOOKMARKS_NOTES';
export const PROGRESS_LABS = 'PROGRESS_LABS';
export const PROGRESS_LESSONS = 'PROGRESS_LESSONS';
export const SETTINGS_NOTIFICATIONS = 'SETTINGS_NOTIFICATIONS';
